### ISSUE TITLE
Release is packaged with a build of Character Select

### ISSUE THREAD

**Issue by Squishy6094** [Coolcord/Yoshi_Pack#1]
This isn't the most helpful as this repository was last updated *months* ago and the packaged version of Character Select is very outdated, Character Select will always be backwards compatible with it's packs so I ask that you either link in your release the [SM64CoopDX Modsite Page](https://mods.sm64coopdx.com/mods/character-select.149/) or the [Github Repository](https://github.com/Squishy6094/character-select-coop) for ease of access.

**Comment by Coolcord** [comment]
The Character Select GitHub Repository is now linked on the release page with the latest release.
